# worker_bees settings
#
# top_level_directory is the shared folder that holds the required_folders
# required_folders are the folders necessary for the queue to run

top_level_directory = 'C:/worker_bees'
required_folders = ['001_queue', '002_running', '003_failed', '004_complete']
